#!/bin/bash

APP="NFR Cleanup"
VERSION="0.4"
LAB_DIR="/opt/firing-range"
YAML_DIR="yaml_backup"
LOG_DIR="logs"
BIN_DIR="bin"
TELNET_DIR="telnet_flag"
SMB_DIR="smb_flag"
NC_DIR="nc_flag"
FTP_DIR="ftp_flag"
WEB_DIR="web_flag"

echo
echo " 🎩  $APP v$VERSION - Lee 'MadHat' Heath <lheath@unspecific.com>"

# Ensure the script exists before continuing
SCRIPT_FILE="$LAB_DIR/$BIN_DIR/launch_random_lab.sh"
if [[ ! -f "$SCRIPT_FILE" ]]; then
  echo "❌ $SCRIPT_FILE not found! Please ensure the script is in place."
  exit 1
fi

# Check for the docker-compose.yml file generated by launch_random_lab.sh
COMPOSE_FILE="$LAB_DIR/docker-compose.yml"
if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "❌ $COMPOSE_FILE not found! Make sure the lab environment was launched first."
  exit 1
fi

# Get the container names from the running lab (docker-compose services)
CONTAINER_NAMES=$(docker compose -f "$COMPOSE_FILE" ps -q)

if [[ -z "$CONTAINER_NAMES" ]]; then
  echo " ℹ️  No containers running for this lab. Proceeding with environment cleanup."
else
  echo " 🛑  Stopping and removing containers..."
  docker compose -f "$COMPOSE_FILE" down
fi

# Remove the specific network for the lab environment (do not remove all networks)
echo " 🌐 Removing lab network (pentest-net)..."
docker network rm pentest-net 2>/dev/null || echo " ⚠️  Network pentest-net not found or already removed."

volumes=$(docker volume ls | grep -v DRIVER | wc -l)

if [[ $volumes > 0 ]]; then
  # Remove volumes associated with the docker-compose setup
  echo " 🗑️  Removing unused Docker volumes..."
  docker volume prune -f
else
  echo " ⚠️  No docker volumes found"
fi

# Clean up generated environment files
echo " 🧹 Cleaning up generated lab files and directories..."
rm -rf "$LAB_DIR/$TELNET_DIR"
rm -rf "$LAB_DIR/$FTP_DIR"
rm -rf "$LAB_DIR/$NC_DIR"
rm -rf "$LAB_DIR/$SMB_DIR"
rm -rf "$LAB_DIR/$WEB_DIR"

# Optionally delete the compose file
# read -p "🗃️ Delete docker-compose.yml as well? (y/n): " DELETE_COMPOSE
#if [[ "$DELETE_COMPOSE" =~ ^[Yy]$ ]]; then
#  rm -f docker-compose.yml
#  echo "✅ Removed docker-compose.yml"
#else
#  echo "📝 Keeping docker-compose.yml"
#qfi

echo " ✅ Lab environment cleanup complete."
echo
